name: CI
on: [push, pull_request]
env:
  GOTOOLCHAIN: local

jobs:
  build-go:
    name: Default build
    strategy:
      matrix:
        go: ['1.20.x', '1.21.x']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-go@v6
      with:
        go-version: ${{ matrix.go }}
    - run: script/cibuild
